## Documents and Fragments

In [2]:
import pandas as pd
import altair as alt

from utils import pgp_csv_paths, chart_dir

documents = pd.read_csv(pgp_csv_paths["documents"])

In [3]:
total_documents = documents.shape[0]
print(f"{total_documents:,} total documents")

35,855 total documents

### Documents by number of fragments

How many fragments are typically used to compose a single document?

The `shelfmark` field in the data is a composite field; a " + " is used to indicate multiple shelfmarks.

NOTE: this does not account for shelfmark overrides, e.g. ranges of shelfmarks.

In [4]:
documents_fragments = documents.copy()

documents_fragments["fragments"] = documents_fragments.shelfmark.apply(lambda x : x.split(' + '))
documents_fragments["num_fragments"] = documents_fragments.fragments.apply(lambda x : len(x))
documents_fragments.num_fragments.value_counts().head(10)

num_fragments
1     34237
2      1224
3       197
4        91
5        46
6        27
8        11
7         8
17        2
13        2
Name: count, dtype: int64

What percent of documents occur on a single fragment?

In [5]:
single_frag_docs = documents_fragments[documents_fragments.num_fragments == 1].shape[0]
single_frag_docs

34237

In [6]:
joins = documents_fragments[documents_fragments.num_fragments > 1].shape[0]
print(f"{joins:,} total joins")

1,618 total joins

What are some examples of documents that span more than 6 fragments?

In [7]:
documents_fragments[documents_fragments.num_fragments > 6][['pgpid', 'shelfmark', 'type', 'description', ]].head(10)

,pgpid,shelfmark,type,description
3975,5371,T-S NS 184.58 + T-S NS 184.62 + T-S NS 184.50 ...,Legal document,"India Book (IB) I, 34a.\r\nLegal proceedings w..."
4167,5634,Bodl. MS heb. f 56/14 + Bodl. MS heb. f 56/15 ...,Literary text,Copy of a story about the edicts against the J...
6371,8297,T-S Ar.50.197 + T-S Ar.50.154 + T-S G1.80 + T-...,Legal query or responsum,Book of responsa. Joins by Amir Ashur. See FGP...
7419,9813,ENA 330.10 + ENA 330.12 + ENA 330.13 + ENA 330...,List or table,"Donations ledger, ca. 1800 CE. There are sever..."
7477,9938,ENA 1066.1 + ENA 1066.2 + ENA 1066.3 + ENA 106...,List or table,"Ledger of accounts, late, of a Venetian merchant."
7482,9952,CUL Or.1080 J253 + T-S Ar.35.382 + T-S Misc.8....,List or table,Ledger of expenses and incomes of the Mustaʿri...
7667,10150,ENA 3450.14 + ENA 3450.17 + ENA 3450.20 + ENA ...,Literary text,Booklet consisting mostly of a text that seems...
7867,10392,ENA 3938.5 + ENA 3938.6 + ENA 3938.7 + ENA 393...,Literary text,Seven pages of an unidentified long-form work ...
8313,10864,ENA 3980.1 + ENA 3980.2 + ENA 3980.3 + ENA 398...,Literary text,Literary text in Arabic script.
8945,11576,ENA NS 77.7 + ENA NS 77.16 + ENA NS 77.17 + EN...,Legal document,Legal document. Seven fragments joined togethe...

In [8]:
# aggregate documents by the number of fragments they span, for graphing
docs_per_num_fragments = documents_fragments[['num_fragments', 'pgpid']].groupby('num_fragments').count().reset_index().rename(columns={"pgpid": "count"})
# calculate a percentage of the total
docs_per_num_fragments["percent"] = docs_per_num_fragments["count"].apply(lambda x : f"{(x / total_documents):.2%}")

docs_per_num_fragments.head(10)

   num_fragments  count percent
0              1  34237  95.49%
1              2   1224   3.41%
2              3    197   0.55%
3              4     91   0.25%
4              5     46   0.13%
5              6     27   0.08%
6              7      8   0.02%
7              8     11   0.03%
8             10      1   0.00%
9             11      2   0.01%

What does the long tail look like, of documents spanning a large number of fragments?

In [9]:
# TODO: think about whether this can be condensed into a meaniengful table to display alongside the chart
docs_per_num_fragments.tail(10)

    num_fragments  count percent
9              11      2   0.01%
10             13      2   0.01%
11             15      1   0.00%
12             16      1   0.00%
13             17      2   0.01%
14             22      1   0.00%
15             25      1   0.00%
16             32      1   0.00%
17             34      1   0.00%
18             64      1   0.00%

In [10]:
# group for display in a table
# - get values for all documents on fewer than 7 fragments
docs_per_nfrags = docs_per_num_fragments[docs_per_num_fragments.num_fragments < 7]
# - aggregate values for 7+
docs_manyfrags = docs_per_num_fragments[docs_per_num_fragments.num_fragments > 7]
total_docs_7plusfrags = docs_manyfrags["count"].sum()
pct_docs_7plusfrags =  f"{(total_docs_7plusfrags / total_documents):.2%}"

agg_values = {"num_fragments": f"{docs_manyfrags.num_fragments.min()}-{docs_manyfrags.num_fragments.max()}", "count": total_docs_7plusfrags, "percent": pct_docs_7plusfrags}
docs_per_nfrags = docs_per_nfrags._append(agg_values, ignore_index=True)
docs_per_nfrags

AttributeError: 'DataFrame' object has no attribute '_append'

In [ ]:
print(docs_per_nfrags.to_latex(index=False))

In [ ]:

docs_frags_chart = alt.Chart(docs_per_num_fragments).mark_bar().encode(
    x=alt.X('num_fragments', title='Number of fragments'),
    y=alt.Y('count', title='Documents').scale(type="symlog")
).properties(
    # title='Documents by number of fragments',
    width=400
)
docs_frags_chart.save(f'{chart_dir}/documents_per_num_frags.pdf')
docs_frags_chart

### Fragments by number of documents

If we use fragments as our starting point, what is the distribution? How many documents are typically written on a fragment, and are there similar outliers?

In [ ]:
fragments = pd.read_csv(pgp_csv_paths["fragments"])
total_fragments = fragments.shape[0]

print(f"{total_fragments:,} fragments")

In the v1.1 dataset, the problem with duplicates in the data export has been corrected.

In [ ]:
print(f"{fragments[fragments.duplicated()].shape[0]:,} duplicates")

In [ ]:
# drop duplicates for now (but should fix in the data export)

uniq_fragments = fragments.drop_duplicates()
total_uniq_fragments = uniq_fragments.shape[0]

print(f"{total_uniq_fragments:,} fragments")

The fragments dataset includes a delimited list of associated PGPIDs; we can use that to determine how many documents are associated with a fragment.

In [ ]:
uniq_fragments["num_documents"] = uniq_fragments.pgpids.apply(lambda x : len(x.split(';')))
uniq_fragments.num_documents.value_counts()

What are some examples of fragments with a large number of documents?

In [ ]:
uniq_fragments[uniq_fragments.num_documents > 6][['shelfmark', 'pgpids', 'num_documents']].head(10)

In [ ]:
# group by number of documents to aggregrate for plotting
frags_per_num_documents = uniq_fragments[['num_documents', 'shelfmark']].groupby('num_documents').count().reset_index().rename(columns={"shelfmark": "fragments"})
# calculate percenatage of total fragements
frags_per_num_documents["percent"] = frags_per_num_documents.fragments.apply(lambda x : (x / total_fragments) * 100)
frags_per_num_documents

In [ ]:
# chart with log scale
frags_docs_chart = alt.Chart(frags_per_num_documents).mark_bar().encode(
    x=alt.X('num_documents', title='Number of Documents', scale=alt.Scale(zero=False)),
    y=alt.Y('fragments', title='Fragments', scale=alt.Scale(type="symlog"))
).properties(
#    title="Fragments by number of documents",
    width=400
)
frags_docs_chart.save(f'{chart_dir}/fragments_with_num_docs.pdf')
frags_docs_chart

In [ ]:

# combine horizontally for display in pdf
(docs_frags_chart | frags_docs_chart).save(f'{chart_dir}/docs_frags_2up.pdf')
(docs_frags_chart | frags_docs_chart).save(f'{chart_dir}/docs_frags_2up.png', ppi=300)
(docs_frags_chart | frags_docs_chart).save(f'{chart_dir}/docs_frags_2up.svg')
(docs_frags_chart | frags_docs_chart)