## Metadata fields available

To what extent are metadata fields filled out?

In [1]:
import pandas as pd
import altair as alt

from utils import pgp_csv_paths, chart_dir

documents = pd.read_csv(pgp_csv_paths["documents"])

total_documents = documents.shape[0]

In [2]:
# calculate what percent of records have which field (code adapted from S&co dataset notebook)
def percent_known(df, field):
  total = len(df)
  with_field = len(df[df[field].notnull()])
  print('%d with %s : %.00f%%' % (with_field, field, (with_field/total)*100))
  return with_field

In [3]:
total_known = {}
metadata_fields = ['type', 'description', 'tags', 'languages_primary', 'languages_secondary', 'doc_date_original', 'doc_date_standard']

for field in metadata_fields:
    total_known[field] = percent_known(documents, field)

print(total_known)

31850 with type : 89%
35854 with description : 100%
16872 with tags : 47%
29886 with languages_primary : 83%
1673 with languages_secondary : 5%
4358 with doc_date_original : 12%
4679 with doc_date_standard : 13%
{'type': 31850, 'description': 35854, 'tags': 16872, 'languages_primary': 29886, 'languages_secondary': 1673, 'doc_date_original': 4358, 'doc_date_standard': 4679}

In [4]:
# are there any records where secondary language is known but primary is not?
documents[documents.languages_primary.isna() & documents.languages_secondary.notna()]

,pgpid,url,iiif_urls,fragment_urls,shelfmark,multifragment,side,region,type,tags,...,inferred_date_standard,inferred_date_rationale,inferred_date_notes,initial_entry,last_modified,input_by,library,collection,has_transcription,has_translation
3218,3995,https://geniza.princeton.edu/documents/3995/,https://cudl.lib.cam.ac.uk/iiif/MS-OR-01080-J-...,https://cudl.lib.cam.ac.uk/view/MS-OR-01080-J-...,CUL Or.1080 J185,NaN,verso,NaN,List or table,"dowry, 13th c, Marriage",...,NaN,NaN,NaN,2004-01-01 05:00:00+00:00,2025-12-02 13:34:00.727351+00:00,Athina Pfeiffer ; Geniza Lab team ; Matthew Du...,CUL,"CUL, Or.",Y,N
9835,12556,https://geniza.princeton.edu/documents/12556/,https://figgy.princeton.edu/concern/scanned_re...,NaN,ENA 3485.4,NaN,NaN,NaN,List or table,list,...,NaN,NaN,NaN,2017-08-01 04:00:00+00:00,2022-08-18 15:13:08.982739+00:00,Amir Ashur ; Marina Rustow,JTS,JTS,N,N
20063,23995,https://geniza.princeton.edu/documents/23995/,NaN,NaN,T-S NS 224.173,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2019-01-01 05:00:00+00:00,2022-03-06 12:46:52.132307+00:00,Amir Ashur ; Marina Rustow,CUL,"CUL, T-S",N,N
21783,25941,https://geniza.princeton.edu/documents/25941/,NaN,NaN,T-S NS 338.53,NaN,NaN,NaN,Legal document,NaN,...,NaN,NaN,NaN,2019-01-01 05:00:00+00:00,2021-12-29 19:19:22.004847+00:00,Alan Elbaum ; Jessica Parker ; Marina Rustow,CUL,"CUL, T-S",N,N
24188,28685,https://geniza.princeton.edu/documents/28685/,https://princetongenizalab.github.io/iiif/jrl/...,https://luna.manchester.ac.uk/luna/servlet/vie...,JRL B 4501,NaN,NaN,NaN,List or table,FGP stub,...,NaN,NaN,NaN,2019-01-01 05:00:00+00:00,2021-09-25 15:58:48.429095+00:00,Amir Ashur ; Marina Rustow,JRL,JRL,N,N

In [5]:
# specify keys as index to preserve field order as specified above
known = pd.DataFrame({'total': total_known}, index=total_known.keys())
known['percent'] = (known['total'] / total_documents*100)
# known['order'] = known.loc.apply(lambda x: metadata_fields.index(x))
known.percent = known.percent.round(2)
known

                     total  percent
type                 31850    88.83
description          35854   100.00
tags                 16872    47.06
languages_primary    29886    83.35
languages_secondary   1673     4.67
doc_date_original     4358    12.15
doc_date_standard     4679    13.05

In [6]:

total_documents = len(documents.index)
known_unknown = pd.DataFrame()
known_unknown['known'] = known['total']
known_unknown['unknown'] = known.total.apply(lambda x: total_documents - x)
known_unknown

                     known  unknown
type                 31850     4005
description          35854        1
tags                 16872    18983
languages_primary    29886     5969
languages_secondary   1673    34182
doc_date_original     4358    31497
doc_date_standard     4679    31176

In [7]:
# reshape for plotting
known_unknown_melted = known_unknown.reset_index().melt(id_vars="index", value_vars=["known", "unknown"])

known_unknown_melted = known_unknown_melted.rename(columns={"index": "field", "variable": "status", "value": "documents"})
known_unknown_melted.head(10)

                 field   status  documents
0                 type    known      31850
1          description    known      35854
2                 tags    known      16872
3    languages_primary    known      29886
4  languages_secondary    known       1673
5    doc_date_original    known       4358
6    doc_date_standard    known       4679
7                 type  unknown       4005
8          description  unknown          1
9                 tags  unknown      18983

In [8]:
field_order = ["type", "description", "tags", "languages_primary", "languages_secondary", "doc_date_original", "doc_date_standard"]

known_melted = known_unknown_melted[known_unknown_melted.status == "known"]

metadata_chart = alt.Chart(known_melted).mark_bar().encode(
    x=alt.X("documents", title="Documents with data populated").scale(domain=[0, total_documents]),
    y=alt.Y("field", title="Metadata field").scale(domain=field_order),
    # color=alt.Color("status").scale(domain=["known", "unknown"], range=["#7bac7b", "lightgray"]),
).properties(width=650, height=200)

metadata_chart

alt.Chart(...)

In [9]:
known_melted['label'] = known_melted.documents.apply(lambda x: f'{x:,} ({x/total_documents:.0%})')

# text labels for metadata chart
text = alt.Chart(known_melted).mark_text(
     dy=0,
     color=alt.expr(alt.expr.if_(alt.datum.documents > 5000, "white", "black")),
     align=alt.expr(alt.expr.if_(alt.datum.documents > 5000, "right", "left")),
     dx=alt.expr(alt.expr.if_(alt.datum.documents > 5000, -10, 5))
  ).encode(
    x=alt.X('documents').scale(domain=[0, total_documents]),
    y=alt.Y("field", title="Metadata field").scale(domain=field_order),
    text=alt.Text('label')
)

(metadata_chart + text).save(f"{chart_dir}/metadata_available.pdf")
metadata_chart + text

/var/folders/mb/6qm4h4yx3yqdy2bv2sjyp4z00000gp/T/ipykernel_96596/3178594534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  known_melted['label'] = known_melted.documents.apply(lambda x: f'{x:,} ({x/total_documents:.0%})')

alt.LayerChart(...)