## Languages and Scripts

### What languages are most common?

In [139]:
import pandas as pd
import polars as pl
import altair as alt

from utils import pgp_csv_paths, chart_dir

documents = pd.read_csv(pgp_csv_paths["documents"])

In [140]:
# combine primary and secondary languages into an all-lang field


def all_langs(row):
  # apparently we can't assume that secondary lang implies primary!
    if pd.notna(row.languages_primary):
      if pd.notna(row.languages_secondary):
        return ','.join([row.languages_primary, row.languages_secondary])
      else:
        return row.languages_primary

    # at least one case has a secondary lang without primary; return it
    if pd.notna(row.languages_secondary):
      return row.languages_secondary

documents['languages_all'] = documents.apply(all_langs, axis=1)
documents[['pgpid', 'languages_primary', 'languages_secondary', 'languages_all']].head()

   pgpid languages_primary languages_secondary    languages_all
0    444     Judaeo-Arabic                 NaN    Judaeo-Arabic
1    445            Hebrew                 NaN           Hebrew
2    446   Aramaic, Hebrew                 NaN  Aramaic, Hebrew
3    447     Judaeo-Arabic                 NaN    Judaeo-Arabic
4    448     Judaeo-Arabic                 NaN    Judaeo-Arabic

In [141]:
documents[documents.languages_primary.isna() & documents.languages_secondary.notna()][["pgpid", "url", "shelfmark"]]

       pgpid                                            url         shelfmark
3218    3995   https://geniza.princeton.edu/documents/3995/  CUL Or.1080 J185
9835   12556  https://geniza.princeton.edu/documents/12556/        ENA 3485.4
20063  23995  https://geniza.princeton.edu/documents/23995/    T-S NS 224.173
21783  25941  https://geniza.princeton.edu/documents/25941/     T-S NS 338.53
24188  28685  https://geniza.princeton.edu/documents/28685/        JRL B 4501

In [142]:
# as we did with tags, split and explode the combined languages into list
documents['langs_all_list'] = documents.languages_all.apply(lambda x: ([l.strip() for l in x.strip().split(",")]) if pd.notna(x) else [])

docs_langs = documents[['pgpid', 'langs_all_list']].explode('langs_all_list').rename(columns={"langs_all_list": "language"})
# filter out unset languages
docs_langs = docs_langs[docs_langs.language.notna()]
# ensure whitespace doesn't cause variation
docs_langs['language'] = docs_langs.language.apply(lambda x : x.strip())

docs_langs.head(10)

    pgpid       language
0     444  Judaeo-Arabic
1     445         Hebrew
2     446        Aramaic
2     446         Hebrew
3     447  Judaeo-Arabic
4     448  Judaeo-Arabic
5     449  Judaeo-Arabic
6     451  Judaeo-Arabic
12    458  Judaeo-Arabic
13    459  Judaeo-Arabic

In [143]:
# total by language, for any occurrence (counting documents multiply)
doc_lang_counts = docs_langs.language.value_counts().reset_index()
doc_lang_counts.head(10)

                           language  count
0                     Judaeo-Arabic  16137
1                            Arabic   9970
2                            Hebrew   7847
3                           Aramaic   1761
4             Greek/Coptic Numerals    976
5                            Ladino    374
6                    Judaeo-Persian    101
7                            French     49
8  Unidentified language and script     39
9                           Spanish     39

How many unique languages total?

In [144]:
total_langs = len(doc_lang_counts.language.unique())
total_langs

55

In [145]:
# create a filter set of most common and unidentified

doc_lang_counts_subset = doc_lang_counts[(doc_lang_counts['count'] > 300) | doc_lang_counts.language.str.contains("Unidentified")].copy()
# format count for output
doc_lang_counts_subset['count'] = doc_lang_counts_subset['count'].apply(lambda x: f"{x:,}")
# rename columns for output
doc_lang_counts_subset = doc_lang_counts_subset.rename(columns={"language": "Language/Script","count": "Documents"})
doc_lang_counts_subset

                     Language/Script Documents
0                      Judaeo-Arabic    16,137
1                             Arabic     9,970
2                             Hebrew     7,847
3                            Aramaic     1,761
4              Greek/Coptic Numerals       976
5                             Ladino       374
8   Unidentified language and script        39
14      Unidentified (Hebrew script)        23
25       Unidentified (Latin script)         8

In [146]:
# document counts for primary language

documents['primary_lang_list'] = documents.languages_primary.apply(lambda x: [l.strip() for l in x.split(',')] if pd.notna(x) else [])
docs_primary_langs = documents[['pgpid', 'primary_lang_list']].explode('primary_lang_list').rename(columns={"primary_lang_list": "primary_language"}).primary_language.value_counts().reset_index()

docs_primary_langs.head(10)

                   primary_language  count
0                     Judaeo-Arabic  15929
1                            Arabic   9305
2                            Hebrew   7114
3                           Aramaic   1648
4             Greek/Coptic Numerals    895
5                            Ladino    365
6                    Judaeo-Persian     98
7                            French     47
8  Unidentified language and script     39
9                           Spanish     39

In [147]:
print(doc_lang_counts_subset.to_latex(index=False))

\begin{tabular}{ll}
\toprule
Language/Script & Documents \\
\midrule
Judaeo-Arabic & 16,137 \\
Arabic & 9,970 \\
Hebrew & 7,847 \\
Aramaic & 1,761 \\
Greek/Coptic Numerals & 976 \\
Ladino & 374 \\
Unidentified language and script & 39 \\
Unidentified (Hebrew script) & 23 \\
Unidentified (Latin script) & 8 \\
\bottomrule
\end{tabular}

### What % of documents have more than one language?

(any language - primary or secondary)

In [148]:
# tally the number of languages using the combined list field we created before
documents['langs_all_count'] = documents.langs_all_list.apply(lambda x: len(x))

documents_with_any_lang = documents[documents.langs_all_count.ne(0)].shape[0]
print(f"{documents_with_any_lang:,} documents with any language")

29,891 documents with any language

### Language combinations

### upSet plot

In [149]:
# limit to languages that occur a sufficient number of times
min_langcount = 200

# identify those languages
lang_subset = doc_lang_counts[doc_lang_counts["count"] > min_langcount].language.to_list()
print('\n'.join(lang_subset))

Judaeo-Arabic
Arabic
Hebrew
Aramaic
Greek/Coptic Numerals
Ladino

In [163]:
# filter to documents with any of those languages
subset_docs_df = doc_df = pl.DataFrame(documents).with_columns(
    # create subset list of languages in the top 300
    subset_langs=pl.col.langs_all_list.list.set_intersection(lang_subset),
    subset_primary_langs=pl.col.primary_lang_list.list.set_intersection(lang_subset),
).filter(
     # filter out documents with no languages in the subset
    pl.col.subset_langs.list.len().gt(0)
)

subset_docs_df.select('langs_all_list', 'primary_lang_list', 'subset_langs', 'subset_primary_langs')

shape: (29_554, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ langs_all_list         ┆ primary_lang_list      ┆ subset_langs           ┆ subset_primary_langs  │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ list[str]              ┆ list[str]              ┆ list[str]              ┆ list[str]             │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]     │
│ ["Hebrew"]             ┆ ["Hebrew"]             ┆ ["Hebrew"]             ┆ ["Hebrew"]            │
│ ["Aramaic", "Hebrew"]  ┆ ["Aramaic", "Hebrew"]  ┆ ["Aramaic", "Hebrew"]  ┆ ["Aramaic", "Hebrew"] │
│ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]     │
│ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]     │
│ …                      ┆ …                      ┆ …                      ┆ …                     │
│ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]     │
│ ["Arabic"]             ┆ ["Arabic"]             ┆ ["Arabic"]             ┆ ["Arabic"]            │
│ ["Arabic"]             ┆ ["Arabic"]             ┆ ["Arabic"]             ┆ ["Arabic"]            │
│ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]      ┆ ["Judaeo-Arabic"]     │
│ ["Arabic",             ┆ ["Arabic",             ┆ ["Arabic",             ┆ ["Arabic",            │
│ "Greek/Coptic Numer…   ┆ "Greek/Coptic Numer…   ┆ "Greek/Coptic Numer…   ┆ "Greek/Coptic Numer…  │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [164]:
# how many J-A in this subset? -> still the expected total
subset_docs_df.filter(pl.col.subset_langs.list.contains("Judaeo-Arabic")).height

16137

In [167]:
# how many primary langs?
subset_docs_df.filter(pl.col.subset_primary_langs.list.contains("Judaeo-Arabic")).height

15929

In [152]:
# categorical 1/0 for set membership
lang_category_columns = [
     pl.col.subset_langs.list.contains(lang).alias(lang).cast(pl.Int32)
    for lang in lang_subset
]



subset_cat_df = subset_docs_df.with_columns(*lang_category_columns)
subset_cat_df.select('subset_langs', *lang_subset)

shape: (29_554, 7)
┌──────────────────────────┬───────────────┬────────┬────────┬─────────┬──────────────┬────────┐
│ subset_langs             ┆ Judaeo-Arabic ┆ Arabic ┆ Hebrew ┆ Aramaic ┆ Greek/Coptic ┆ Ladino │
│ ---                      ┆ ---           ┆ ---    ┆ ---    ┆ ---     ┆ Numerals     ┆ ---    │
│ list[str]                ┆ i32           ┆ i32    ┆ i32    ┆ i32     ┆ ---          ┆ i32    │
│                          ┆               ┆        ┆        ┆         ┆ i32          ┆        │
╞══════════════════════════╪═══════════════╪════════╪════════╪═════════╪══════════════╪════════╡
│ ["Judaeo-Arabic"]        ┆ 1             ┆ 0      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ ["Hebrew"]               ┆ 0             ┆ 0      ┆ 1      ┆ 0       ┆ 0            ┆ 0      │
│ ["Aramaic", "Hebrew"]    ┆ 0             ┆ 0      ┆ 1      ┆ 1       ┆ 0            ┆ 0      │
│ ["Judaeo-Arabic"]        ┆ 1             ┆ 0      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ ["Judaeo-Arabic"]        ┆ 1             ┆ 0      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ …                        ┆ …             ┆ …      ┆ …      ┆ …       ┆ …            ┆ …      │
│ ["Judaeo-Arabic"]        ┆ 1             ┆ 0      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ ["Arabic"]               ┆ 0             ┆ 1      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ ["Arabic"]               ┆ 0             ┆ 1      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ ["Judaeo-Arabic"]        ┆ 1             ┆ 0      ┆ 0      ┆ 0       ┆ 0            ┆ 0      │
│ ["Arabic", "Greek/Coptic ┆ 0             ┆ 1      ┆ 0      ┆ 0       ┆ 1            ┆ 0      │
│ Numer…                   ┆               ┆        ┆        ┆         ┆              ┆        │
└──────────────────────────┴───────────────┴────────┴────────┴─────────┴──────────────┴────────┘

In [153]:
# check that we still have the expected number of Judaeo-Arabic documents
subset_cat_df.filter(pl.col("Judaeo-Arabic").eq(1)).shape[0]

16137

In [172]:
import altair_upset as au

# Create an UpSet plot
upset_chart = au.UpSetAltair(
    # data=lang_memberships_df.to_pandas(),
    data=subset_cat_df.select(lang_subset).to_pandas(),
    sets=lang_subset,
    # title="Sample UpSet Plot",
    sort_by="frequency",
    sort_order="descending",
    glyph_size=100,  # Ensure positive size
    set_label_bg_size=500,  # Ensure positive size
    line_connection_size=2,
    vertical_bar_y_axis_orient='left',
    highlight=[0],
    color_range=['#3A3A3A'],   # override colors to avoid distracting
    width=1150,  # enough space that numbers don't overlap
    height=600,
)

upset_chart = upset_chart.configure_legend(disable=True).configure_axis(labelFontWeight="normal")

upset_chart.save(f"{chart_dir}/languages_upset_plot.png") # ppi=300 not supported by altair_upset
upset_chart.save(f"{chart_dir}/languages_upset_plot.svg")
upset_chart