## Dates and Calendars

In [1]:
import polars as pl
import altair as alt

from utils import pgp_csv_paths, chart_dir

documents = pl.read_csv(pgp_csv_paths["documents"])

### Documents by date

Date on document or inferred date

In [2]:
# limit to documents with standard date OR inferred date information
dated_docs = documents.filter(pl.col("doc_date_standard").is_not_null() | pl.col("inferred_date_standard").is_not_null())
dated_docs.select('doc_date_standard', 'doc_date_original', 'doc_date_calendar', 'inferred_date_standard')

shape: (5_961, 4)
┌───────────────────────┬──────────────────────┬───────────────────┬────────────────────────┐
│ doc_date_standard     ┆ doc_date_original    ┆ doc_date_calendar ┆ inferred_date_standard │
│ ---                   ┆ ---                  ┆ ---               ┆ ---                    │
│ str                   ┆ str                  ┆ str               ┆ str                    │
╞═══════════════════════╪══════════════════════╪═══════════════════╪════════════════════════╡
│ 1258-08-31/1259-09-19 ┆ 1570                 ┆ Seleucid          ┆ null                   │
│ null                  ┆ null                 ┆ null              ┆ 1160/1166              │
│ null                  ┆ null                 ┆ null              ┆ 1089/1190              │
│ null                  ┆ null                 ┆ null              ┆ 1168/1204              │
│ null                  ┆ null                 ┆ null              ┆ 1213/1237              │
│ …                     ┆ …                    ┆ …                 ┆ …                      │
│ 1564-09-07/1564-11-04 ┆ Tishrei–Ḥeshvan 5325 ┆ Anno Mundi        ┆ null                   │
│ null                  ┆ null                 ┆ null              ┆ 1564                   │
│ 1563-11-22            ┆ 6 Kislev 5324        ┆ Anno Mundi        ┆ null                   │
│ 1563-12-16            ┆ 30 Kislev 5324       ┆ Anno Mundi        ┆ null                   │
│ 1565-04-12            ┆ 11 Iyyar 5325        ┆ Anno Mundi        ┆ null                   │
└───────────────────────┴──────────────────────┴───────────────────┴────────────────────────┘

In [59]:
# how many documents with inferred dates?
documents.filter(pl.col("inferred_date_standard").is_not_null()) #.height

shape: (1_307, 30)
┌───────┬────────────┬────────────┬────────────┬───┬─────────┬────────────┬────────────┬───────────┐
│ pgpid ┆ url        ┆ iiif_urls  ┆ fragment_u ┆ … ┆ library ┆ collection ┆ has_transc ┆ has_trans │
│ ---   ┆ ---        ┆ ---        ┆ rls        ┆   ┆ ---     ┆ ---        ┆ ription    ┆ lation    │
│ i64   ┆ str        ┆ str        ┆ ---        ┆   ┆ str     ┆ str        ┆ ---        ┆ ---       │
│       ┆            ┆            ┆ str        ┆   ┆         ┆            ┆ str        ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═════════╪════════════╪════════════╪═══════════╡
│ 453   ┆ https://ge ┆ null       ┆ null       ┆ … ┆ NLR     ┆ NLR        ┆ N          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 454   ┆ https://ge ┆ null       ┆ null       ┆ … ┆ NLR     ┆ NLR        ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 458   ┆ https://ge ┆ null       ┆ null       ┆ … ┆ BL      ┆ BL         ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 459   ┆ https://ge ┆ null       ┆ null       ┆ … ┆ BL      ┆ BL         ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 482   ┆ https://ge ┆ null       ┆ null       ┆ … ┆ BL      ┆ BL         ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …       ┆ …          ┆ …          ┆ …         │
│ 41120 ┆ https://ge ┆ null       ┆ null       ┆ … ┆ NLR     ┆ NLR        ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 41121 ┆ https://ge ┆ null       ┆ null       ┆ … ┆ NLR     ┆ NLR        ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 41123 ┆ https://ge ┆ null       ┆ null       ┆ … ┆ NLR     ┆ NLR        ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│ 41331 ┆ https://ge ┆ https://cu ┆ https://cu ┆ … ┆ CUL     ┆ CUL, T-S   ┆ N          ┆ N         │
│       ┆ niza.princ ┆ dl.lib.cam ┆ dl.lib.cam ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆ .ac.uk//ii ┆ .ac.uk/vie ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆ …          ┆ …          ┆   ┆         ┆            ┆            ┆           │
│ 41517 ┆ https://ge ┆ null       ┆ null       ┆ … ┆ NLR     ┆ NLR        ┆ Y          ┆ N         │
│       ┆ niza.princ ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
│       ┆ …          ┆            ┆            ┆   ┆         ┆            ┆            ┆           │
└───────┴────────────┴────────────┴────────────┴───┴─────────┴────────────┴────────────┴───────────┘

In [3]:
# collect dates into a single field
dated_docs = dated_docs.with_columns(
    date=pl.when(pl.col("doc_date_standard").is_not_null()).then(pl.col("doc_date_standard").str.strip_chars()).otherwise(pl.col("inferred_date_standard").str.strip_chars())
)
dated_docs.select('doc_date_standard', 'doc_date_original', 'doc_date_calendar', 'inferred_date_standard', 'date')

shape: (5_961, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ doc_date_standard ┆ doc_date_original ┆ doc_date_calendar ┆ inferred_date_sta ┆ date             │
│ ---               ┆ ---               ┆ ---               ┆ ndard             ┆ ---              │
│ str               ┆ str               ┆ str               ┆ ---               ┆ str              │
│                   ┆                   ┆                   ┆ str               ┆                  │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 1258-08-31/1259-0 ┆ 1570              ┆ Seleucid          ┆ null              ┆ 1258-08-31/1259- │
│ 9-19              ┆                   ┆                   ┆                   ┆ 09-19            │
│ null              ┆ null              ┆ null              ┆ 1160/1166         ┆ 1160/1166        │
│ null              ┆ null              ┆ null              ┆ 1089/1190         ┆ 1089/1190        │
│ null              ┆ null              ┆ null              ┆ 1168/1204         ┆ 1168/1204        │
│ null              ┆ null              ┆ null              ┆ 1213/1237         ┆ 1213/1237        │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ 1564-09-07/1564-1 ┆ Tishrei–Ḥeshvan   ┆ Anno Mundi        ┆ null              ┆ 1564-09-07/1564- │
│ 1-04              ┆ 5325              ┆                   ┆                   ┆ 11-04            │
│ null              ┆ null              ┆ null              ┆ 1564              ┆ 1564             │
│ 1563-11-22        ┆ 6 Kislev 5324     ┆ Anno Mundi        ┆ null              ┆ 1563-11-22       │
│ 1563-12-16        ┆ 30 Kislev 5324    ┆ Anno Mundi        ┆ null              ┆ 1563-12-16       │
│ 1565-04-12        ┆ 11 Iyyar 5325     ┆ Anno Mundi        ┆ null              ┆ 1565-04-12       │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [4]:
dated_docs.filter(pl.col("date").str.contains("1217-02-29")).select('doc_date_standard', 'doc_date_original', 'doc_date_calendar', 'inferred_date_standard', 'date')

shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ doc_date_standard ┆ doc_date_original ┆ doc_date_calendar ┆ inferred_date_sta ┆ date             │
│ ---               ┆ ---               ┆ ---               ┆ ndard             ┆ ---              │
│ str               ┆ str               ┆ str               ┆ ---               ┆ str              │
│                   ┆                   ┆                   ┆ str               ┆                  │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 1217-02-20/1217-0 ┆ middle decade of  ┆ Seleucid          ┆ null              ┆ 1217-02-20/1217- │
│ 2-29              ┆ Adar 1528         ┆                   ┆                   ┆ 02-29            │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [5]:
dated_docs.filter(pl.col("date").str.contains("1139/")).select('pgpid', 'doc_date_standard', 'doc_date_original', 'doc_date_calendar', 'inferred_date_standard', 'date')

shape: (3, 6)
┌───────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┬───────────┐
│ pgpid ┆ doc_date_standard ┆ doc_date_original ┆ doc_date_calendar ┆ inferred_date_st ┆ date      │
│ ---   ┆ ---               ┆ ---               ┆ ---               ┆ andard           ┆ ---       │
│ i64   ┆ str               ┆ str               ┆ str               ┆ ---              ┆ str       │
│       ┆                   ┆                   ┆                   ┆ str              ┆           │
╞═══════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╪═══════════╡
│ 4666  ┆ 1139/1140         ┆ 1451              ┆ Seleucid          ┆ null             ┆ 1139/1140 │
│ 9103  ┆ null              ┆ null              ┆ null              ┆ 1139/1140        ┆ 1139/1140 │
│ 9104  ┆ null              ┆ null              ┆ null              ┆ 1139/1140        ┆ 1139/1140 │
└───────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┴───────────┘

In [147]:
# Use undate to parse the original dates based on calendar

from lark.exceptions import UnexpectedEOF, VisitError
from undate.date import UnInt
from undate import Undate, UndateInterval, Calendar

def parse_original_date(doc_date_calendar, doc_date_original):
    if doc_date_calendar == "Anno Mundi":
        undate_calendar = Calendar.HEBREW
    elif doc_date_calendar == "Hijrī":
        undate_calendar = "Islamic"
    elif doc_date_calendar == "Seleucid":
        undate_calendar = "Seleucid"
    else:
        return

    try:
        return Undate.parse(doc_date_original, undate_calendar)
    except (VisitError, ValueError, UnexpectedEOF):
        # we don't support parsing everything in this dataset, and some of them have errors
        # for demonstration purposes, ignore anything we can't parse
        pass


days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]

def parse_date_range(datestr):
    try:
        return Undate.parse(datestr, "EDTF")
    except Exception:
        # at least one is an inaccurate/invalid date - Feb 29 on a non leap year
        pass


docs_with_undate = (
    dated_docs.with_columns(
        # parse standardized date (document date or inferred) for graphing across calendars, inferred and date on document
        undate_std=pl.col("date").map_elements(parse_date_range, return_dtype=pl.Object),
        # parse original date based on calendar
        undate_orig=pl.struct(
            "doc_date_calendar", "doc_date_original"
        ).map_elements(
            lambda x: parse_original_date(
                x["doc_date_calendar"], x["doc_date_original"]
            ),
            return_dtype=pl.Object,
        )
    )
    .with_columns(
        # compare undate standardized earliest/latest values with the standardized dates in the dataset
        undate_earliest=pl.col("undate_std").map_elements(
            lambda x: x.earliest, return_dtype=pl.Object
        ),
        undate_latest=pl.col("undate_std").map_elements(
            lambda x: x.latest, return_dtype=pl.Object
        ),
        # string versions, for cast to date for filtering
        undate_earliest_str=pl.col("undate_std").map_elements(
            lambda x: str(x.earliest), return_dtype=pl.String
        ),
        undate_latest_str=pl.col("undate_std").map_elements(
            lambda x: str(x.latest), return_dtype=pl.String
        ),
        # years as integers
        undate_earliest_year=pl.col("undate_std").map_elements(
            lambda x: x.earliest.year if isinstance(x, Undate) else x.earliest.earliest.year, return_dtype=pl.Int32
        ),
        undate_latest_year=pl.col("undate_std").map_elements(
            lambda x: x.latest.year if isinstance(x, Undate) else x.latest.latest.year, return_dtype=pl.Int32
        ),
       #  undate_midpoint=pl.col("undate_std").map_elements(
       #      lambda x: x.earliest + (x.latest - x.earliest)/2.0, return_dtype=pl.datatypes.Object
       # ),
       # undate_midpoint_year=pl.col("undate_std").map_elements(
       #      lambda x: (x.earliest + (x.latest - x.earliest)/2.0).year, return_dtype=pl.Int32
       # ),
        # orig_date_precision=pl.col("undate_std").map_elements(
        #     lambda x: str(x.precision).lower(),
        #     return_dtype=pl.datatypes.String,
        # ),
        # determine weekday when possible
        undate_weekday=pl.col("undate_orig").map_elements(
            lambda x: days[x.earliest.weekday]
            if x.earliest == x.latest
            else None,
            return_dtype=pl.datatypes.String,
        ),
        # get numeric month in original calendar, when known
        undate_month=pl.col("undate_orig").map_elements(
            lambda x: x.month,
            return_dtype=pl.datatypes.String,
        ),
        # add field to distinguish type of date, for graphing
        date_source=pl.when(pl.col("inferred_date_standard").is_not_null()).then(pl.lit("Inferred")).otherwise(pl.lit("On document")),
        # add durations
        date_duration_days=pl.col("undate_std").map_elements(
            # if duration is ambiguous, take the larger value
            lambda x: x.duration().days.upper if isinstance(x.duration().days, UnInt) else x.duration().days, return_dtype=pl.datatypes.Int32)
    ).with_columns(
    #     # use previously calculated duration in days to calculate years or portion of years
        date_duration_years=pl.col("date_duration_days").truediv(365),
    ).with_columns(
        undate_midpoint_year=pl.col("undate_earliest_year") + ((pl.col("undate_latest_year") - pl.col("undate_earliest_year")) / 2)
    )
)

# a typo in a date in pgpid 1284 resulted in a date of 41502 - ignore that one!
docs_with_undate = docs_with_undate.filter(pl.col("undate_latest_year").le(2500))

docs_with_undate.select('doc_date_standard', 'doc_date_original', 'doc_date_calendar', 'inferred_date_standard', 
                        'date', 'undate_orig', 'undate_earliest', 'undate_latest', 'undate_midpoint_year',
                       'date_source', 'undate_earliest_year', 'undate_latest_year')

shape: (5_956, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ doc_date_ ┆ doc_date_ ┆ doc_date_ ┆ inferred_ ┆ … ┆ undate_mi ┆ date_sour ┆ undate_ea ┆ undate_l │
│ standard  ┆ original  ┆ calendar  ┆ date_stan ┆   ┆ dpoint_ye ┆ ce        ┆ rliest_ye ┆ atest_ye │
│ ---       ┆ ---       ┆ ---       ┆ dard      ┆   ┆ ar        ┆ ---       ┆ ar        ┆ ar       │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ f64       ┆           ┆ i32       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1258-08-3 ┆ 1570      ┆ Seleucid  ┆ null      ┆ … ┆ 1258.5    ┆ On        ┆ 1258      ┆ 1259     │
│ 1/1259-09 ┆           ┆           ┆           ┆   ┆           ┆ document  ┆           ┆          │
│ -19       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ null      ┆ null      ┆ null      ┆ 1160/1166 ┆ … ┆ 1163.0    ┆ Inferred  ┆ 1160      ┆ 1166     │
│ null      ┆ null      ┆ null      ┆ 1089/1190 ┆ … ┆ 1139.5    ┆ Inferred  ┆ 1089      ┆ 1190     │
│ null      ┆ null      ┆ null      ┆ 1168/1204 ┆ … ┆ 1186.0    ┆ Inferred  ┆ 1168      ┆ 1204     │
│ null      ┆ null      ┆ null      ┆ 1213/1237 ┆ … ┆ 1225.0    ┆ Inferred  ┆ 1213      ┆ 1237     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1564-09-0 ┆ Tishrei–Ḥ ┆ Anno      ┆ null      ┆ … ┆ 1564.0    ┆ On        ┆ 1564      ┆ 1564     │
│ 7/1564-11 ┆ eshvan    ┆ Mundi     ┆           ┆   ┆           ┆ document  ┆           ┆          │
│ -04       ┆ 5325      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ null      ┆ null      ┆ null      ┆ 1564      ┆ … ┆ 1564.0    ┆ Inferred  ┆ 1564      ┆ 1564     │
│ 1563-11-2 ┆ 6 Kislev  ┆ Anno      ┆ null      ┆ … ┆ 1563.0    ┆ On        ┆ 1563      ┆ 1563     │
│ 2         ┆ 5324      ┆ Mundi     ┆           ┆   ┆           ┆ document  ┆           ┆          │
│ 1563-12-1 ┆ 30 Kislev ┆ Anno      ┆ null      ┆ … ┆ 1563.0    ┆ On        ┆ 1563      ┆ 1563     │
│ 6         ┆ 5324      ┆ Mundi     ┆           ┆   ┆           ┆ document  ┆           ┆          │
│ 1565-04-1 ┆ 11 Iyyar  ┆ Anno      ┆ null      ┆ … ┆ 1565.0    ┆ On        ┆ 1565      ┆ 1565     │
│ 2         ┆ 5325      ┆ Mundi     ┆           ┆   ┆           ┆ document  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [86]:
# check that we haven't lost inferred dates in the parsing step
docs_with_undate.filter(pl.col("date_source").eq("Inferred")).height

1304

In [8]:
# test filtering by year range
docs_with_undate.filter(pl.col("undate_earliest_year").ge(1500) & pl.col("undate_latest_year").le(1550)).head()

shape: (5, 45)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ pgpid ┆ url        ┆ iiif_urls  ┆ fragment_u ┆ … ┆ undate_mo ┆ date_sour ┆ date_dura ┆ date_dura │
│ ---   ┆ ---        ┆ ---        ┆ rls        ┆   ┆ nth       ┆ ce        ┆ tion_days ┆ tion_year │
│ i64   ┆ str        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ s         │
│       ┆            ┆            ┆ str        ┆   ┆ str       ┆ str       ┆ i32       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4522  ┆ https://ge ┆ https://fi ┆ null       ┆ … ┆ null      ┆ On        ┆ 354       ┆ 0.969863  │
│       ┆ niza.princ ┆ ggy.prince ┆            ┆   ┆           ┆ document  ┆           ┆           │
│       ┆ eton.edu/d ┆ ton.edu/co ┆            ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆ …          ┆            ┆   ┆           ┆           ┆           ┆           │
│ 8225  ┆ https://ge ┆ https://cu ┆ https://cu ┆ … ┆ 07        ┆ On        ┆ 1         ┆ 0.00274   │
│       ┆ niza.princ ┆ dl.lib.cam ┆ dl.lib.cam ┆   ┆           ┆ document  ┆           ┆           │
│       ┆ eton.edu/d ┆ .ac.uk/iii ┆ .ac.uk/vie ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆ …          ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ 8280  ┆ https://ge ┆ null       ┆ null       ┆ … ┆ 06        ┆ On        ┆ 1         ┆ 0.00274   │
│       ┆ niza.princ ┆            ┆            ┆   ┆           ┆ document  ┆           ┆           │
│       ┆ eton.edu/d ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ 9015  ┆ https://ge ┆ https://cu ┆ https://cu ┆ … ┆ 12        ┆ On        ┆ 29        ┆ 0.079452  │
│       ┆ niza.princ ┆ dl.lib.cam ┆ dl.lib.cam ┆   ┆           ┆ document  ┆           ┆           │
│       ┆ eton.edu/d ┆ .ac.uk/iii ┆ .ac.uk/vie ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆ …          ┆ …          ┆   ┆           ┆           ┆           ┆           │
│ 10215 ┆ https://ge ┆ https://fi ┆ null       ┆ … ┆ null      ┆ On        ┆ 354       ┆ 0.969863  │
│       ┆ niza.princ ┆ ggy.prince ┆            ┆   ┆           ┆ document  ┆           ┆           │
│       ┆ eton.edu/d ┆ ton.edu/co ┆            ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆ …          ┆            ┆   ┆           ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [35]:
# count documents by date overlap for arbitrary date segments, for both types of dates

earliest = min(docs_with_undate['undate_earliest_year'].to_list())
latest = max(docs_with_undate['undate_latest_year'].to_list())
start_year = round(earliest, -2)
end_year = round(latest, -1)

start_year, end_year

(800, 1900)

In [10]:
# this is a data error in v1.1 data
docs_with_undate.filter(pl.col("undate_latest_year").ge(2500))

shape: (1, 45)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ pgpid ┆ url        ┆ iiif_urls  ┆ fragment_u ┆ … ┆ undate_mo ┆ date_sour ┆ date_dura ┆ date_dura │
│ ---   ┆ ---        ┆ ---        ┆ rls        ┆   ┆ nth       ┆ ce        ┆ tion_days ┆ tion_year │
│ i64   ┆ str        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ s         │
│       ┆            ┆            ┆ str        ┆   ┆ str       ┆ str       ┆ i32       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1284  ┆ https://ge ┆ https://cu ┆ https://cu ┆ … ┆ 02        ┆ On        ┆ 1         ┆ 0.00274   │
│       ┆ niza.princ ┆ dl.lib.cam ┆ dl.lib.cam ┆   ┆           ┆ document  ┆           ┆           │
│       ┆ eton.edu/d ┆ .ac.uk/iii ┆ .ac.uk/vie ┆   ┆           ┆           ┆           ┆           │
│       ┆ …          ┆ …          ┆ …          ┆   ┆           ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [132]:
# chunk size
year_segment_size = 10

# generate a dataframe with years based on the desired range and segment size
half_cent_df = pl.DataFrame(data={'years': list(range(start_year, end_year + year_segment_size, year_segment_size))}).with_columns(
    interval=pl.col("years").map_elements(lambda x: UndateInterval(Undate(x), Undate(x + year_segment_size)), return_dtype=pl.datatypes.Object),
    earliest=pl.col("years"),
    latest=pl.col("years").add(year_segment_size)
)

# do a conditional join on the dated documents, then group and count
half_cent_df = half_cent_df.join_where(
    docs_with_undate,
    pl.col("undate_earliest_year").le(pl.col("latest")) & pl.col("undate_latest_year").gt(pl.col("earliest")),
).group_by("earliest", "date_source").agg(pl.len().alias("count"), pl.first("interval"), pl.first("latest")).sort("earliest")

half_cent_df.tail(10)

shape: (10, 5)
┌──────────┬─────────────┬───────┬───────────┬────────┐
│ earliest ┆ date_source ┆ count ┆ interval  ┆ latest │
│ ---      ┆ ---         ┆ ---   ┆ ---       ┆ ---    │
│ i64      ┆ str         ┆ u32   ┆ object    ┆ i64    │
╞══════════╪═════════════╪═══════╪═══════════╪════════╡
│ 1850     ┆ On document ┆ 11    ┆ 1850/1860 ┆ 1860   │
│ 1860     ┆ On document ┆ 14    ┆ 1860/1870 ┆ 1870   │
│ 1860     ┆ Inferred    ┆ 35    ┆ 1860/1870 ┆ 1870   │
│ 1870     ┆ On document ┆ 13    ┆ 1870/1880 ┆ 1880   │
│ 1870     ┆ Inferred    ┆ 35    ┆ 1870/1880 ┆ 1880   │
│ 1880     ┆ On document ┆ 14    ┆ 1880/1890 ┆ 1890   │
│ 1880     ┆ Inferred    ┆ 35    ┆ 1880/1890 ┆ 1890   │
│ 1890     ┆ On document ┆ 8     ┆ 1890/1900 ┆ 1900   │
│ 1890     ┆ Inferred    ┆ 35    ┆ 1890/1900 ┆ 1900   │
│ 1900     ┆ On document ┆ 7     ┆ 1900/1910 ┆ 1910   │
└──────────┴─────────────┴───────┴───────────┴────────┘

In [130]:
half_cent_df.filter(pl.col("date_source").eq("Inferred"))

shape: (96, 5)
┌──────────┬─────────────┬───────┬───────────┬────────┐
│ earliest ┆ date_source ┆ count ┆ interval  ┆ latest │
│ ---      ┆ ---         ┆ ---   ┆ ---       ┆ ---    │
│ i64      ┆ str         ┆ u32   ┆ object    ┆ i64    │
╞══════════╪═════════════╪═══════╪═══════════╪════════╡
│ 940      ┆ Inferred    ┆ 8     ┆ 0940/0950 ┆ 950    │
│ 950      ┆ Inferred    ┆ 8     ┆ 0950/0960 ┆ 960    │
│ 960      ┆ Inferred    ┆ 10    ┆ 0960/0970 ┆ 970    │
│ 970      ┆ Inferred    ┆ 9     ┆ 0970/0980 ┆ 980    │
│ 980      ┆ Inferred    ┆ 9     ┆ 0980/0990 ┆ 990    │
│ …        ┆ …           ┆ …     ┆ …         ┆ …      │
│ 1850     ┆ Inferred    ┆ 35    ┆ 1850/1860 ┆ 1860   │
│ 1860     ┆ Inferred    ┆ 35    ┆ 1860/1870 ┆ 1870   │
│ 1870     ┆ Inferred    ┆ 35    ┆ 1870/1880 ┆ 1880   │
│ 1880     ┆ Inferred    ┆ 35    ┆ 1880/1890 ┆ 1890   │
│ 1890     ┆ Inferred    ┆ 35    ┆ 1890/1900 ┆ 1900   │
└──────────┴─────────────┴───────┴───────────┴────────┘

In [141]:
# these numbers are wrong! we're not getting enough matches

half_cent_df.group_by(pl.col("date_source")).agg(pl.sum("count"))

shape: (2, 2)
┌─────────────┬───────┐
│ date_source ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ On document ┆ 5514  │
│ Inferred    ┆ 7274  │
└─────────────┴───────┘

In [155]:
# plot as a stacked bar chart, colored by date source

# width 15 for 25 year range
# width 8 for 10 year range

bar_chart = alt.Chart(half_cent_df.select('earliest', 'latest', 'date_source', 'count')).mark_bar(opacity=0.3, width=6).encode(
    x=alt.X('earliest', title="Year", axis=alt.Axis(format="r")).scale(domain=[850, 1950]),
    # x2='latest',t
    y=alt.Y('count', title='Documents by decade').scale(domain=[0, 900]),
    color=alt.Color("date_source", title="Dating").scale(domain=['On document', 'Inferred']),  # specify domain to control order
).properties(width=900, height=175)
bar_chart

alt.Chart(...)

In [91]:
# too many records for altair to count, aggregate in polars

docs_by_midpoint = docs_with_undate.group_by(pl.col("undate_midpoint_year")).agg(pl.len().alias("count"))
docs_by_midpoint.head()

shape: (5, 2)
┌──────────────────────┬───────┐
│ undate_midpoint_year ┆ count │
│ ---                  ┆ ---   │
│ f64                  ┆ u32   │
╞══════════════════════╪═══════╡
│ 989.0                ┆ 6     │
│ 1729.5               ┆ 1     │
│ 1105.0               ┆ 13    │
│ 1646.0               ┆ 3     │
│ 1688.5               ┆ 1     │
└──────────────────────┴───────┘

In [162]:
##### alt.data_transformers.enable("vegafusion")

# NOTE: we have to clip because the midpoint aggregation is a huge spike
line_chart = alt.Chart(docs_by_midpoint).mark_line(opacity=0.6, color="green", interpolate="monotone", clip=True).encode(
 x=alt.X('undate_midpoint_year', title="Year", axis=alt.Axis(format="r")).scale(domain=[850, 1950]),
 y=alt.Y('count', title='Documents (midpoint)').scale(domain=[0, 450]),
).properties(width=900, height=175)

line_chart

alt.Chart(...)

In [163]:
combined_dating_chart = (bar_chart + line_chart).configure_legend(
    strokeColor='gray',
    fillColor='white', #EEEEEE',
    padding=10,
    cornerRadius=5,
    orient='top-left'
).resolve_scale(x='shared', y='independent')

combined_dating_chart.save(f'{chart_dir}/combined_dating.pdf')
combined_dating_chart

alt.LayerChart(...)

In [149]:
# date precision chart is not used in the essay

date_precision_chart = alt.Chart(docs_with_undate.select('pgpid', 'date_duration_years', 'date_source')).mark_boxplot(opacity=0.5).encode(
    x=alt.X('date_duration_years', title="Date precision (duration in years)"),
    y=alt.Y("date_source", title="").scale(domain=['On document', 'Inferred']),  # specify domain to control order
    color=alt.Color("date_source", title="Dating").scale(domain=['On document', 'Inferred']).legend(None),  # specify domain to control order
).properties(width=900)
date_precision_chart.save(f'{chart_dir}/date_precision.pdf')
date_precision_chart

alt.Chart(...)

In [150]:
docs_with_undate['date_duration_years'].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 5956.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 11.879843  │
│ std        ┆ 33.583644  │
│ min        ┆ 0.00274    │
│ 25%        ┆ 0.00274    │
│ 50%        ┆ 0.084932   │
│ 75%        ┆ 2.0        │
│ max        ┆ 701.465753 │
└────────────┴────────────┘

In [152]:
docs_with_undate.filter(pl.col("date_source").eq("On document"))["date_duration_years"].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 4652.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 2.334758   │
│ std        ┆ 12.116641  │
│ min        ┆ 0.00274    │
│ 25%        ┆ 0.00274    │
│ 50%        ┆ 0.079452   │
│ 75%        ┆ 0.972603   │
│ max        ┆ 102.068493 │
└────────────┴────────────┘

In [153]:
docs_with_undate.filter(pl.col("date_source").eq("Inferred"))["date_duration_years"].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 1304.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 45.931788  │
│ std        ┆ 56.078792  │
│ min        ┆ 0.00274    │
│ 25%        ┆ 25.016438  │
│ 50%        ┆ 39.024658  │
│ 75%        ┆ 39.027397  │
│ max        ┆ 701.465753 │
└────────────┴────────────┘

In [ ]:
# doc_date_stats = dated_docs[dated_docs.date_source == 'On document'].date_duration_years.describe().to_dict()
# doc_date_stats['type'] = 'On document'
# inferred_date_stats = dated_docs[dated_docs.date_source == 'Inferred'].date_duration_years.describe().to_dict()
# inferred_date_stats
# inferred_date_stats['type'] = 'Inferred'

# date_stats_df = pd.DataFrame([doc_date_stats, inferred_date_stats])
# date_stats_df[['type', 'count', 'mean', 'max']]

In [109]:
# print(date_stats_df[['type', 'count', 'mean', 'max']].to_latex())

### Calendars

In [103]:
# graph documents with calendars

# limit to documents with standard date; fill unset calendar with "Unspecified"
dated_docs_cal = docs_with_undate.filter(pl.col("doc_date_standard").is_not_null()).with_columns(
    pl.col("doc_date_calendar").fill_null("Unspecified")
)

In [107]:

docs_calendars_charts = alt.Chart(dated_docs_cal.select('pgpid', 'undate_midpoint_year', 'doc_date_calendar')).mark_area(opacity=0.7).encode(
  x=alt.X('undate_midpoint_year', title="CE Year (Julian/Gregorian)", bin=alt.Bin(maxbins=120), axis=alt.Axis(format="r")),
  y=alt.Y('count(pgpid)', title='Documents'),
  color=alt.Y("doc_date_calendar", title="Calendar")
).properties(width=900, height=200).configure_legend(
    strokeColor='gray',
    fillColor='white', #EEEEEE',
    padding=10,
    cornerRadius=5,
    orient='top-left'
)

docs_calendars_charts.save(f"{chart_dir}/dated_docs_by_cal.pdf")
docs_calendars_charts

alt.Chart(...)