## Scholarship records

In [1]:
import pandas as pd
import altair as alt

from utils import pgp_csv_paths

sources = pd.read_csv(pgp_csv_paths["sources"])
sources.head()

,source_type,authors,title,journal_book,volume,issue,year,place_published,publisher,edition,other_info,page_range,languages,url,notes,citation,slug,num_footnotes
0,Unpublished,"Masback, Grace",NaN,NaN,NaN,NaN,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created from PGPID 17049,"Grace Masback, (2020).",masback-grace-unpublished-2020,1
1,Unpublished,"Khan, Geoffrey ; Rustow, Marina",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created from PGPID 30838,Geoffrey Khan and Marina Rustow.,khan-geoffrey-rustow-marina-unpublished-2,2
2,Unpublished,"Eliyahu, Ayala Meyer",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created from PGPID 29689,Ayala Meyer Eliyahu.,eliyahu-ayala-meyer-unpublished,1
3,Unpublished,"Perez, Idan",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created from PGPID 31295,Idan Perez.,perez-idan-unpublished,3
4,Unpublished,"Ben-Sasson, Menahem",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created from PGPID 11665,Menahem Ben-Sasson.,ben-sasson-menahem-unpublished,1

In [2]:
print(f"{sources.shape[0]:,} sources")

712 sources

In [3]:
sources.source_type.value_counts().reset_index()

    source_type  count
0   Unpublished    287
1       Article    250
2          Book     97
3  Book Section     56
4  Dissertation     21
5          Blog      1

In [4]:
source_totals = sources.groupby('source_type').agg(
    count=pd.NamedAgg(column="source_type", aggfunc="count"),
    num_footnotes=pd.NamedAgg(column='num_footnotes', aggfunc='sum')
    ).reset_index()
source_totals = source_totals.sort_values('count', ascending=False)
source_totals = source_totals.rename(columns={"source_type": "Type", "count": "Sources", "num_footnotes": "Footnotes"})
source_totals

           Type  Sources  Footnotes
5   Unpublished      287      15289
0       Article      250        672
2          Book       97       7208
3  Book Section       56        224
4  Dissertation       21       1021
1          Blog        1          1

In [5]:
print(source_totals.to_latex(index=False))

\begin{tabular}{lrr}
\toprule
Type & Sources & Footnotes \\
\midrule
Unpublished & 287 & 15289 \\
Article & 250 & 672 \\
Book & 97 & 7208 \\
Book Section & 56 & 224 \\
Dissertation & 21 & 1021 \\
Blog & 1 & 1 \\
\bottomrule
\end{tabular}

In [6]:
# how many documents do sources relate to?
# goitein sources - split out into volumes to wrangle the scale
# what does it look like if we leave Goitein out?

sources.num_footnotes.value_counts().reset_index().sort_values("num_footnotes").head(10)

    num_footnotes  count
4               0     29
0               1    246
1               2    118
2               3     49
3               4     34
5               5     20
6               6     14
10              7      9
9               8      9
7               9     11

In [7]:
source_authors = sources.copy()
source_authors["author_list"] = sources.authors.apply(lambda x : x.split(';') if pd.notna(x) else None)
source_authors.head()
source_authors = source_authors[['source_type', 'title', 'author_list']].explode("author_list").rename(columns={"author_list": "author"})
# filter out unset authors
source_authors = source_authors[source_authors.author.notna()]

source_authors["author"] = source_authors.author.apply(lambda x: x.strip())
source_authors.head(10)

   source_type title                author
0  Unpublished   NaN        Masback, Grace
1  Unpublished   NaN        Khan, Geoffrey
1  Unpublished   NaN        Rustow, Marina
2  Unpublished   NaN  Eliyahu, Ayala Meyer
3  Unpublished   NaN           Perez, Idan
4  Unpublished   NaN   Ben-Sasson, Menahem
5  Unpublished   NaN     Vanthieghem, Naïm
6  Unpublished   NaN        Perlman, Yaara
6  Unpublished   NaN        Picard, Joshua
7  Unpublished   NaN            Gil, Moshe

In [8]:
print(f"{len(source_authors.author.unique()):,} unique authors")

189 unique authors

In [9]:
source_authors.author.value_counts().head(12)

author
Goitein, S. D.               197
Elbaum, Alan                  71
Rustow, Marina                63
Umrethwala, Yusuf             51
Friedman, Mordechai Akiva     42
Gil, Moshe                    20
Ashur, Amir                   18
Vanthieghem, Naïm             17
Khan, Geoffrey                16
Dudley, Matthew               15
Zinger, Oded                  13
David, Avraham                12
Name: count, dtype: int64